version: '3.4'

services:
  mijnapp-backend:
    container_name: mijnapp-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=40443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert/test.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPassword
      - ORIGINS=http://localhost:60080
      - JwtClaimEncryption__SecretKey=1234567890ABCDEF
      - Jwt__Key=df32d6192fdf2907dfe14f2c42e7316505236350a4c35195c1bbd4159360b90a
      - Jwt__Issuer=MijnApp
      - DigidCgi__SiamServer=https://alsiam.s-hertogenbosch.nl/aselectserver/server
      - DigidCgi__ApplicationId=Denbosch_Verhuizen
      - DigidCgi__SiamServerName=alsiam.s-hertogenbosch.nl
      - DigidCgi__CertificatePath=/app/cert/verhuizen.accp.s-hertogenbosch.nl.pfx
      - DigidCgi__CertificatePassword=!changeMe!
      - HasFakeLoginEnabled=true
      - Api__AddressApiKey=!changeMe!
      - Api__BrpApiKey=!changeMe!
      - Api__OrderApiKey=!changeMe!
      - Api__OrderTypeApiKey=!changeMe!
      - Api__ProcessApiKey=!changeMe!
      - Api__WebResourceApiKey=!changeMe!
      - Api__ContractApiKey=aaaaaaaaaaaaaaaa
      - DigidCgi__SharedSecret=!changeMe!
    ports:
      - "40080:80"
      - "40443:443"
      
  mijnapp-frontend:
    container_name: mijnapp-frontend
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=60443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/cert/test.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPassword
      - PublicSettings__BACKEND_URL=http://localhost:40080
      - PublicSettings__HAS_FAKE_INLOG_ENABLED=true
    ports:
      - "60080:80"
      - "60443:443"
